### ISSUE TITLE
Errore funzione file

### ISSUE THREAD

**Issue by zSavT** [zSavT/lazy-shell#12]
Sto utilizzando le funzioni per i file, ad ogni esecuzione anche se viene creato un file da sempre l'errore che "il file non può essere aperto", ora non vorrei che il messaggio esca anche se in realtà è stato aperto correttamente o effettivamente non riesce ad aprire il file.

`file NomeFile("file.txt","r");`

Crea quel problema.

**Comment by AlessandroCarella** [comment]
Sei sicuro di non aver sbagliato qualcosa?
Magari il file che vuoi aprire non è nella stessa directory del main.cpp o simil?
Ho testato la funzione con l'apertura in lettura e funzionava tutto quindi mi sembra strano che non funzioni.

**Comment by zSavT** [comment]
> @zSavT
> Sei sicuro di non aver sbagliato qualcosa?
> Magari il file che vuoi aprire non è nella stessa directory del main.cpp o simil?
> Ho testato la funzione con l'apertura in lettura e funzionava tutto quindi mi sembra strano che non funzioni.

Ho caricato i file sul main, così puoi controllare personalmente.

**Comment by zSavT** [comment]
Risolto

**Comment by AlessandroCarella** [comment]
Hai chiamato ricorsivamente la funzione menuPrincipale ()....
