### ISSUE TITLE
Migliorare il costrutture della classe all'interno del file "file.h" in modo tale che l'apertura dei file sia uguale a quella in C

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/lazy-shell#14]
Ad esempio l'apertura con il tag "w" non crea un file come in C ma apre un file preesistente in scrittura

**Comment by AlessandroCarella** [comment]
Ho effettuato alcuni test e in verità funziona già come in C nel modo in cui ho scritto il modulo (costruttore); non avendo trattato l'utilizzo dei file in cpp nel corso di asd non sapevo di aver fatto bene.

**Comment by zSavT** [comment]
> Ho effettuato alcuni test e in verità funziona già come in C nel modo in cui ho scritto il modulo (costruttore); non avendo trattato l'utilizzo dei file in cpp nel corso di asd non sapevo di aver fatto bene.

In quindi che tipo di miglioramenti vuoi fare dopo questa considerazione?

**Comment by AlessandroCarella** [comment]
Mi avevi fatto venire il dubbio che non funzionasse come pensavo, sopratutto per la funzione di apertura del file (e la relativa creazione nel caso non esistesse).
Ho fatto delle prove e invece funziona nel modo in cui l'avevo pensata.
