### ISSUE TITLE
Richiesta funzione

### ISSUE THREAD

**Issue by zSavT** [zSavT/lazy-shell#5]
@AlessandroCarella crea una funzione generica nel modulo "**file.h**" che permette di aprire, un file txt che ha come input il tipo di lettura e il percorso. Infine crea una funzione che permette di chiudere un file.

**Comment by AlessandroCarella** [comment]
@zSavT ti odio ❤️

**Comment by AlessandroCarella** [comment]
I file in cpp funzionano in un modo un po' diverso: https://www.cplusplus.com/doc/tutorial/files/
la funzione di apertura del file posso farla in modo tale che funzioni come su C pero mi devi dire tu se va bene?
Ad esempio potrei aprire il file in input se viene mandata la stringa "r" (deve essere una stringa perché ci sono le aperture tipo "br" (o rb ora non ricordo, comunque è la lettura dei file binari).
(a quanto ricordo non si può passare una stringa tipo visto che (ad esempio) "ios::out" ovviamente è diverso da ios::out come comando.
Io preferirei farla con la nomenclatura di c (quindi "r", "rb",...) non per altro ma sono abituato e altri linguaggi usano una cosa simile comunque.

**Comment by zSavT** [comment]
> @zSavT
> I file in cpp funzionano in un modo un po' diverso: https://www.cplusplus.com/doc/tutorial/files/
> la funzione di apertura del file posso farla in modo tale che funzioni come su C pero mi devi dire tu se va bene?
> Ad esempio potrei aprire il file in input se viene mandata la stringa "r" (deve essere una stringa perché ci sono le aperture tipo "br" (o rb ora non ricordo, comunque è la lettura dei file binari).
> (a quanto ricordo non si può passare una stringa tipo visto che (ad esempio) "ios::out" ovviamente è diverso da ios::out come comando.
> Io preferirei farla con la nomenclatura di c (quindi "r", "rb",...) non per altro ma sono abituato e altri linguaggi usano una cosa simile comunque.

Ok, implementa come su C.

**Comment by AlessandroCarella** [comment]
@zSavT 
cosa preferisci ci sia quando un file non puo essere aperto?
io metterei:
```
    cout<<"il file non puo essere aperto"<<endl;

    system("pause");

    exit(1);
```
in modo da comunicare il fallimento nella lettura e la successiva uscita dal programma.

**Comment by zSavT** [comment]
Ci sta.
