### ISSUE TITLE
Implementazione di altri metodi per la classe file

### ISSUE THREAD

**Issue by AlessandroCarella** [zSavT/lazy-shell#7]
La classe file ha bisogno di altri metodi per leggere, scrivere etc
Linko la reference che ho usato nella realizzazione iniziale della classe in modo da poter fare riferimento li
https://www.cplusplus.com/doc/tutorial/files/

**Comment by zSavT** [comment]
Allora, implementa un metodo che permette di leggere una intera riga da file e la memorizza in un vettore di stringhe, la dimenzione di questo vettore deve essere pari al numero di righe presenti nel file. In più deve controllare il primo carattere di ogni stringa e se questo primo carattere è uguale ad un carattere speciale (come per esempio '#'), non deve leggere quella riga per intero e deve passare alla riga successiva. Allego un file txt di esempio su come deve essere formatto il file txt. In questo caso la prima riga deve essere memorizzata per intero e la seconda no.
Al posto del vettore, puoi utilizzare anche altre strutture dati che più preferisci, l'importante è poter memorizzare tutte le righe presenti nel file.

[esempio.txt](https://github.com/zSavT/lazy-shell/files/6246480/esempio.txt)




![tenor](https://user-images.githubusercontent.com/55914219/113353505-0e2cbb00-933e-11eb-84ed-5aafdee0ec7b.gif)

**Comment by AlessandroCarella** [comment]
va bene l'implementazione con le liste di asd? i vettori funzionano in modo diverso e secondo me le liste sono più facili da usare in generale.

**Comment by AlessandroCarella** [comment]
Issue risolta con la pull request#10
